[package]
name = "janus-streaming-rs"
version = "0.1.0"
authors = ["Aleksey Ivanov <ialexxei@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
amy = "0.8"
cstr-macro = "0.1.0"
janus-plugin = "*"
lazy_static = "*"
serde_json = "1.0"
